version: "3"

services:
  shorten:
    image: shorten:latest
    environment:
      SHORTEN_DSN: ${SHORTEN_DSN:-"user='postgres' password='' host='db-host' port=5432 dbname='shorten' sslmode=disable options='-c statement_timeout=60000'"}
      SHORTEN_ADDR: ":8080"
    ports:
      - 8081:8080
    restart: unless-stopped
    networks:
      - traefik_proxy
    extra_hosts:
      # for access external database
      - "db-host:host-gateway"

networks:
  traefik_proxy:
    external: true