version: "3"

services:
  shorten:
    image: shorten:latest
    environment:
      SHORTEN_DSN: ""
      SHORTEN_ADDR: ":8080"
    ports:
      - 8080:8080
    restart: always
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external: true