version: "3.8"
services:
  shorten:
    build: .
    container_name: shorten-app
    ports:
      - "80:8080"
    depends_on:
      - redis
    environment:
      SHORTEN_DOMAIN: "http://localhost"
      SHORTEN_REDIS_ADDR: redis:6379
      SHORTEN_REDIS_PASSWORD:
      SHORTEN_REDIS_DB: 0
      SHORTEN_BLOOM_FILTER_EXPECTED_INSERTIONS: 10000000
      SHORTEN_BLOOM_FILTER_FPP: 0.00001
      SHORTEN_BLOOM_FILTER_HASH_SEED: 0x1
  redis:
    image: redis:latest
    container_name: shorten-redis
    hostname: redis
    ports: 
      - "6379:6379"
