version: "3"

services:
  shorten:
    image: shorten:latest
    environment:
      SHORTEN_DSN: "user='postgres' password='' host='localhost' port=15433 dbname='shorten' sslmode=disable options='-c statement_timeout=60000'"
      SHORTEN_ADDR: ":8080"
    ports:
      - 8081:8080
    restart: always
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external: true