version: "3"

services:
  shorten:
    image: shorten:latest
    container_name: shorten
    environment:
      SHORTEN_DSN: ${SHORTEN_DSN:-"user='postgres' password='' host='db-host' port=5432 dbname='shorten' sslmode=disable options='-c statement_timeout=60000'"}
      SHORTEN_ADDR: ${SHORTEN_ADDR:-"shorten:80"}
    restart: unless-stopped
    networks:
      - traefik_proxy
    extra_hosts:
      # for access external database
      - "db-host:host-gateway"

networks:
  traefik_proxy:
    external: true